# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 786ba5a76333cea1a56dbd27b6ea7a46d0013332dc222ee3b5887743adc82886cb40a77f16c068d11331efb4aee95c1204936937bb580e9652eca6307b0ffbf9

test:
  secret_key_base: 03c65b8e6f928617afc1f64e63254df7a2357030e48f6f22b9cb02425089f95d5844b8caf2561014c3445b60edaca45e9867699335e854a04c4211215f5b10d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
